name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.0

      # Step 3: Install dependencies and run tests
      - name: Install dependencies and run tests
        run: |
          go mod tidy
          go test ./...

  docker:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/snip:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/snip:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      # Step 1: Deploy using SSH
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd github/snip.elginbrian.com
            git pull https://github.com/elginbrian/snip.elginbrian.com.git
            go mod vendor
            docker-compose down
            docker-compose up --build -d

      # Step 2: Run database migrations
      - name: Run database migrations
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd github/snip.elginbrian.com
            docker exec snipelginbriancom_db_1 /bin/sh -c "migrate -path ./db/migrations -database 'postgres://user:password@localhost:5432/url_shortener?sslmode=disable' up"
